id: IA29AC91C
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:27:40.329946
last_modified: 2023-02-08 15:27:40.330038
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  356B:
    base_file: 356B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
